title: Govy Theme
email: your-email@example.com
description: >- 
  A simple blog template based on GOV.UK design patterns.
url: "https://telatin.github.io" # the base hostname & protocol for your site
baseurl: "/govy-theme" # the subpath of your site, e.g. /blog
twitter_username: jekyllrb
github_username: jekyll

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:title/
